config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :projects do
    resources :transactions, only: %i[new create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :transactions, dependent: :destroy
  has_many :users, through: :transactions

  validates :name, :goal_amount, presence: true

  scope :achieved, -> {where(achieved: true)}
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  belongs_to :project

  validates :amount, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :transactions, dependent: :destroy
  has_many :projects, through: :transactions

  validates :first_name, :last_name, presence: true
  validates :email, presence: true, uniqueness: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  
  def home
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[show]
  before_action :set_user, only: %i[ show]
  before_action :uniq_name_project_per_user, only: :create

  def index
    @projects = current_user.projects.distinct
  end

  def new
    @project = Project.new
  end

  def create
    @current_user_id = current_user.id
    @project = ProjectCreator.new(
      name: project_params[:name],
      goal_amount: project_params[:goal_amount],
      start_date: project_params[:start_date],
      end_date: project_params[:end_date],
      current_user_id: @current_user_id).call
    if @project.persisted?
      redirect_to project_path(@project)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @transaction = Transaction.new
  end

  private

  def project_params
    params.require(:project).permit(:name, :goal_amount, :start_date, :end_date)
  end

  def set_project
    @project = Project.find(params[:id])
  end

  def set_user
    @user = current_user
  end

  def uniq_name_project_per_user
    @project = Project.new(project_params)
    if Project.joins(:transactions).where(transactions: {user_id: current_user.id}).pluck(:name).include?(project_params[:name])
      flash[:alert] = "You already have a project named like this 😬"
      render :new, status: :unprocessable_entity
    end
  end

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def new
    @transaction = Transaction.new
    @transaction.project = Project.find(params[:project_id])
    @transaction.user = current_user
  end

  def create
    @transaction = Transaction.new(transaction_params)
    @transaction.user = User.first
    @transaction.project = Project.find(params[:project_id])

    if @transaction.save!
      # @transaction.project = Project.find(params[:project_id])
      new_amount = @transaction.amount += @transaction.project.current_amount
      @transaction.project.update!(current_amount: new_amount)

      redirect_to project_path(@transaction.project)
    else
      render :new
    end
  end

  private

  def transaction_params
    params.require(:transaction).permit(:project_id, :user_id, :amount)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gambare</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Welcome to Gambare</h1>
<p>Start now</p>

<%= link_to "Money tracking", new_project_path %>

app/views/projects/index.html.erb
<h1>All projects</h1>

<div class="content d-flex justify-content-between">
  <div class="card-content row mb-3">
    <% @projects.each do |project| %>
    <div class="card col-3 mt-2">
      <div class="card-body">
        <h5 class="card-title"><%= link_to project.name, project_path(project) %></h5>
        <p><%= project.users.map { |u| u.first_name }.uniq.join(", ") %></p>
      </div>
    </div>
    <% end %>
  </div>
</div>
<%= link_to "Create new project", new_project_path(@project)  %>

app/views/projects/new.html.erb
<%= simple_form_for @project do |f| %>
  <%= f.input :name %>
  <%= f.input :goal_amount %>
  <%= f.input :start_date %>
  <%= f.input :end_date %>
  <%= f.submit "Let's do it!" %>
<% end %>

app/views/projects/show.html.erb
<h1><%= @project.name %></h1>

<div class="row">
  <div class="col-6">
    <ul>
      <li>Goal: <%= @project.goal_amount %>$</li>
      <li>Current amount: <%= @project.current_amount %>$</li>
    </ul>

    <% if @project.current_amount <= @project.goal_amount %>
      <div class="alert-danger" >
        Hang in there
      </div>
      <% else %>
      <div class="alert-success" >
      Project completed, well done!
      </div>
    <% end %>

    <%= render "transactions/form", project: @project, transaction: @transaction %>
  </div>

  <div class="col-6">
    <h3>Tasks : </h3>
  </div>
</div>
<%= link_to "Back", projects_path  %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Projects", projects_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Notifications", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <small class="nav-link"> Hello <%= current_user.first_name %></small>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Money", "#", class: "dropdown-item" %>
              <%= link_to "Fitness", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/transactions/_form.html.erb
<%= simple_form_for [@project, @transaction] do |f| %>
  <%= f.input :amount %>
  <%= f.submit "Go!" %>
<% end %>